databases:
  - name: postgres
    ipAllowList: []
    databaseName: web_server_production
    user: web_server
    plan: free

services:
  - type: web
    name: web_server
    plan: free
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        